library(data.table)
library(tidyverse) 	
library(psych)     	
library(dplyr)    
library(REdaS)     
library(GPArotation)
library(mclust)    
library(plotly)	
library(tableone)
library(survminer)
library(survival)
library(cmprsk)
library(gridExtra)
library(autoReg)
library(interactionR)
library(ggplot2)
library(glmnet)
library(doParallel)
library(foreach)
library(gtools)
library(ggsci)
library(extrafont)
library(readxl)
library(mediation) 
library(broom)
library(magrittr) 

loadfonts(device = "win")